FROM node:20-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy application source
COPY . .

EXPOSE 5173
ENV DOCKER=true

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
